#!/bin/tcsh
# script_Cartesian_IC [nProcs]
# Script for creation of initial conditions.
# Run from turquoise on an interactive session.
# Juan A. Saenz, based on scripts by Mark Petersen and Doug Jacobsen.

if ($1 == '') then 
  set nProcs = 2
else 
  set nProcs = $1
endif

# ******* step 1: create periodic hexagonal Voronoi Tesselation file
module purge
module load intel
rm graph.info*
rm *.nc
./periodic_grid 
mv grid.nc step1_grid.nc

# ******* step 2: Convert to MPAS grid
./MpasMeshConverter.x step1_grid.nc step2_mesh.nc

# ******* step 3: add cullCells variable
source /usr/projects/climate/SHARED_CLIMATE/scripts/mustang_intel_openmpi.csh
cp namelist.ocean_init.step3 namelist.ocean_init
mpirun -np  $nProcs ocean_init_model 
mv output.0000-01-01_00.00.00.nc step3_mesh_w_cellmask.nc

# ******* step 4: cull cells, create graph.info files
module purge
module load intel
module use /usr/projects/climate/SHARED_CLIMATE/modulefiles/all
module load metis
setenv NETCDF /usr/projects/climate/COMMON_MPAS/software/mustang/gnu-openmpi/netcdf-3.6.3
./MpasCellCuller.x step3_mesh_w_cellmask.nc step4_culled_mesh.nc
mkdir -p files_before_culling
mv graph.info* log* files_before_culling
mv culled_graph.info graph.info
kmetis graph.info $nProcs
kmetis graph.info 24
kmetis graph.info 16
kmetis graph.info 8
kmetis graph.info 4

# ******* step 5: Add initial conditions
source /usr/projects/climate/SHARED_CLIMATE/scripts/mustang_intel_openmpi.csh
cp namelist.ocean_init.step5 namelist.ocean_init
mpirun -np $nProcs ocean_init_model 
mv output.0000-01-01_00.00.00.nc step5_ocean.nc

